# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aguay <aguay@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/08/31 08:51:26 by mmondell          #+#    #+#              #
#    Updated: 2022/03/09 08:03:43 by aguay            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#*#######################################################
##*          ERASE COMMENTS FOR BONUS PARTS            ##
#*#######################################################

## -----  NAME OF THE PROGRAMM ----- ##
NAME 			= libft.a 

## ----- CHOOSE COMPILER AND FLAGS ----- ##
CC				= gcc
CFLAGS			= -Wall -Wextra -Werror -c

## ----- PATH TO FOLDERS ----- ##
SRCS_DIR		= srcs/

OBJ_DIR			= obj/

INCLUDE_DIR		= includes/

LIBFT_DIR		= libft/

## ----- SOURCE FILES ----- ##
SRCS_FILES		= ft_atoi.c			\
			  ft_bzero.c			\
			  ft_calloc.c			\
			  ft_isalnum.c			\
			  ft_isalpha.c			\
			  ft_isascii.c			\
			  ft_isdigit.c			\
			  ft_isprint.c			\
			  ft_itoa.c			\
			  ft_lstadd_back.c		\
			  ft_lstadd_front.c		\
			  ft_lstclear.c			\
			  ft_lstdelone.c		\
			  ft_lstiter.c			\
			  ft_lstlast.c			\
			  ft_lstmap.c			\
			  ft_lstnew.c			\
			  ft_lstsize.c			\
			  ft_memchr.c			\
			  ft_memcmp.c			\
			  ft_memcpy.c			\
			  ft_memmove.c			\
			  ft_memset.c			\
			  ft_print_chars.c		\
			  ft_print_dui.c		\
			  ft_printf.c			\
			  ft_putchar_fd.c		\
			  ft_putendl_fd.c		\
			  ft_puthex.c			\
			  ft_putnbr_fd.c		\
			  ft_putnbr_unsigned_fd.c	\
			  ft_putstr_fd.c		\
			  ft_split.c			\
			  ft_strchr.c			\
			  ft_strdup.c			\
			  ft_striteri.c			\
			  ft_strjoin.c			\
			  ft_strlcat.c			\
			  ft_strlcpy.c			\
			  ft_strlen.c			\
			  ft_strmapi.c			\
			  ft_strncmp.c			\
			  ft_strnstr.c			\
			  ft_strrchr.c			\
			  ft_strtrim.c			\
			  ft_substr.c			\
			  ft_tolower.c			\
			  ft_toupper.c			\
			  ft_utoa.c			\

## ----- .C TO .O CONVERT ----- ##
OBJ_FILES		= $(SRCS_FILES:.c=.o)

## ----- ADDPREFIX TO FILES ----- ##
# MAIN PROGRAMM #
SRCS			= $(addprefix $(SRCS_DIR), $(SRCS_FILES))
OBJS			= $(addprefix $(OBJ_DIR), $(OBJ_FILES))
VPATH			= $(SRCS_DIR)
#--------------------------------------------------------------#

## ----- TOOLS AND COLORS ----- ##
RM				= rm -Rf
NO_PRINT		= --no-print-directory
RED 			= \033[31m
GREEN 			= \033[32m
YELLOW 			= \033[33m
BLUE 			= \033[34m
PINK 			= \033[35m
AQUA 			= \033[36m
GREY 			= \033[37m
UNDERLINE 		= \033[4m
NORMAL 			= \033[0m

## ----- ALL ACTION DEPENDENCIES AND RECIPE FOR MAIN PROGRAM ----- ##
all: obj $(NAME)
	@echo "$(GREEN)Compilation Completed Successfully$(NORMAL)"

$(OBJ_DIR)%.o:%.c
	$(CC) $(CFLAGS) -I $(INCLUDE_DIR) -o $@ -c $<

$(NAME): $(OBJS)
	ar rc $(NAME) $(OBJS)
	ranlib $(NAME)

obj:
	@clear
	@echo "$(RED) Making TonyG C library $(AQUA)"
	@mkdir -p $(OBJ_DIR)

## ----- CLEAN COMMANDS ----- ##
clean:
	$(RM) $(OBJS) $(B_OBJS)
	@rm -rf $(OBJ_DIR)

fclean: clean
	@rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
